// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qacrvdqrdymlxdfcubgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhY3J2ZHFyZHltbHhkZmN1YmdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNjU0NDMsImV4cCI6MjA1OTk0MTQ0M30.aYf4eL4eERDN7exa8n_DP_gbbga0muPGkYWZIHxZkuQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);